services:
  - docker

before_script:
  # updating back rights
  - docker-compose -f  docker/docker-compose.exec.yml run --user='root' --entrypoint chown node -R node:node . 
  # updating front rights
  - docker-compose -f  docker/docker-compose.exec.yml run --user='root' -w /home/node/app/front --entrypoint chown node -R node:node . 

script:
  - ./packaging/build.sh --distantdeploy
