#!  /bin/bash

: ${ARCH:="x86"}

echo $ARCH

ARCH="-$ARCH" docker-compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml down
ARCH="-$ARCH" docker-compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml up
