#!  /bin/bash

set -e

: ${ARCH:="x86"}

export ARCH="-${ARCH}"
export ACTION=${1:-server}

./npm-back run build
docker-compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml down
docker-compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml up --abort-on-container-exit


#EOF
