version: '3'

services:
  server:
    build:
      context: ../
      dockerfile: ./docker/server/Dockerfile
    image: rlegrand/beets-webapp${ARCH}
    ports:
      - 80:80
  redis:
    image: redis
    command: "redis-server --appendonly yes"
    volumes:
      - ./dbdata:/data/

    
