version: '3'

services:
  server:
    volumes:
      - ../back:/app/back
      - ../front/dist:/app/front
      - dbdata:/app/data
    command: ${ACTION}
  ng:
    build: ../docker/dev/ngcli/
    volumes:
      - ../front:/app/
    command: build --watch      

volumes:
  dbdata:
    driver: local
