version: '3'

services:
  # ng exec
  ng:
    image: "ngcli"
    user: node
    build: ../docker/dev/ngcli/
    volumes:
      - ../front:/app/
  # node/npm executables
  node:
    image: node:10-jessie
    user: node
    working_dir: /home/node/app/front
    volumes:
      - ../front/:/home/node/app/front
      - ../back/:/home/node/app/back
