version: '3'

services:
  server:
    volumes:
      - ../back:/app/back
      - ../front/dist:/app/front
      - ../ignore/dbdata:/app/data
    entrypoint: ["npm", "run", "dev", "--"]
    command: ${ACTION}
  ng:
    build: ../docker/dev/ngcli/
    volumes:
      - ../front:/app/
    command: build --watch      

